[package]
name = "sometruckthing"
version = "0.1.0"
authors = ["Lilith645 <lilith@inet-sys.com>","Charlotte Lily Fields <charlottelilyfields48@gmail.com>"]

[dependencies]
glium = "0.15.0"
glutin = "*"
